import React from 'react'
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Акції',
  description: 'Generated by create next app',
}

export default function DiscountsLayout({ children }: {children: React.ReactNode}) {
  return (
    <div className='main'>
      {children}
    </div>
  )
}
