import React from 'react';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Наші заклади',
  description: 'Generated by create next app',
}

export default function PlaceLayout({ children }: {children: React.ReactNode}) {
  return (
    <div>
      {children}
    </div>
  )
}
