import type { Metadata } from 'next';
import './globals.css';
import  Header from '../components/header/page';
import Footer from '../components/footer/page';
import styles from './layout.module.scss';

export const metadata: Metadata = {
  title: 'Food delivery',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Header />
          <div className={styles.container}>
            {children}
          </div>
          <Footer />
      </body>
    </html>
  )
}
