import type { Metadata } from 'next';
import './globals.css';
import  Header from '../components/header/Header';
import Footer from '../components/footer/Footer';
import styles from './layout.module.scss';
import { Providers } from '@/components/providers/Provider';
import { UpButton } from '@/components/ui/upbutton/UpButton';

export const metadata: Metadata = {
  title: 'Food delivery',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Header />
          <div className={styles.container}>
            {children}
          </div>
          <UpButton />
          <Footer />
        </Providers>
      </body>
    </html>
  )
}
