import React from 'react'
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Суші',
  description: 'Generated by create next app',
}

export default function Sushilayout({ children }: {children: React.ReactNode}) {
  return (
    <div>
      {children}
    </div>
  )
}